"""Web research MCP server — search, fetch, and summarise web pages."""
import os
import re
import time
import urllib.parse
import httpx
from bs4 import BeautifulSoup
from mcp.server.fastmcp import FastMCP

OLLAMA_BASE_URL = os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434")
OLLAMA_MODEL = os.environ.get("OLLAMA_MODEL", "llama3.2")

mcp = FastMCP("web-research")

_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/120.0.0.0 Safari/537.36"
    )
}


def _clean(text: str, max_chars: int = 3000) -> str:
    text = re.sub(r"\n{3,}", "\n\n", text)
    text = re.sub(r" {2,}", " ", text)
    return text.strip()[:max_chars]


def _ollama(prompt: str) -> str:
    with httpx.Client(timeout=60) as client:
        resp = client.post(
            f"{OLLAMA_BASE_URL}/api/generate",
            json={"model": OLLAMA_MODEL, "prompt": prompt, "stream": False},
        )
        resp.raise_for_status()
        return resp.json().get("response", "").strip()


def _fetch_text(url: str) -> str:
    with httpx.Client(timeout=10, follow_redirects=True, headers=_HEADERS) as client:
        resp = client.get(url)
        resp.raise_for_status()
    soup = BeautifulSoup(resp.text, "html.parser")
    for tag in soup(["script", "style", "nav", "footer", "header"]):
        tag.decompose()
    return _clean(soup.get_text(separator="\n"))


@mcp.tool()
def search_web(query: str) -> str:
    """Search DuckDuckGo and return the top 5 results with titles, URLs, and snippets."""
    encoded = urllib.parse.quote_plus(query)
    url = f"https://html.duckduckgo.com/html/?q={encoded}"

    for attempt in range(3):
        with httpx.Client(timeout=15, follow_redirects=True, headers=_HEADERS) as client:
            resp = client.get(url)

        if resp.status_code == 202:
            time.sleep(2 * (attempt + 1))
            continue

        resp.raise_for_status()

        soup = BeautifulSoup(resp.text, "html.parser")
        results = soup.select(".result__body")[:5]
        if not results:
            if attempt < 2:
                time.sleep(1.5)
                continue
            return "No results found."

        lines = []
        for i, r in enumerate(results, 1):
            title_el = r.select_one(".result__a")
            snippet_el = r.select_one(".result__snippet")
            title = title_el.get_text(strip=True) if title_el else "No title"
            href = title_el.get("href", "") if title_el else ""
            snippet = snippet_el.get_text(strip=True) if snippet_el else ""
            lines.append(f"{i}. {title} - {href}\n   {snippet}")

        return "\n\n".join(lines)

    return "No results found (search temporarily unavailable)."


@mcp.tool()
def fetch_url(url: str) -> str:
    """Fetch a web page and return its cleaned text content (up to 3000 chars)."""
    try:
        return _fetch_text(url)
    except Exception as exc:
        return f"Error fetching {url}: {exc}"


@mcp.tool()
def summarize_url(url: str) -> str:
    """Fetch a web page and return a 3-5 sentence summary generated by the local LLM."""
    try:
        text = _fetch_text(url)
    except Exception as exc:
        return f"Error fetching {url}: {exc}"

    prompt = f"Summarize this in 3-5 clear sentences:\n\n{text}"
    try:
        return _ollama(prompt)
    except Exception as exc:
        return f"LLM error: {exc}"


if __name__ == "__main__":
    mcp.run(transport="stdio")
